Webshop.UI/Pages/Checkout/Checkout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Card;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ModelDTO;
using Webshop.UI.DataAccess;

namespace Webshop.UI.Pages.Checkout
{
    public class CheckoutModel : PageModel
    {
        private readonly IDataAccess _dataaccess;

        public CheckoutModel(IDataAccess dataaccess)
        {
            _dataaccess = dataaccess;
        }
        
        [BindProperty]
        public CreditCard card { get; set; }
        public string Feedback { get; set; }
        public string Alert { get; set; }
        [BindProperty]
        public ShoppingCartDTO Cart { get; set; }
        public void OnGet(int id)
        {
            Cart = _dataaccess.GetShoppingCart(id);
        }
        public IActionResult OnPostPay(int id)
        {
            if (ModelState.IsValid)
            {
                if (_dataaccess.CardForms(card.CreditCardNumber, card.SecurityCode))
                {
                    Cart = _dataaccess.GetShoppingCart(id);
                    _dataaccess.SaveRecipt(Cart.CartId);
                    _dataaccess.ClearCartById(id);
                    return RedirectToPage("/Checkout/RecieptHistory", new { id = Cart.CartId});
                }
                else if (!_dataaccess.CardForms(card.CreditCardNumber, card.SecurityCode))
                {
                    Feedback = "Invalid creditcard number or security code";
                    Alert = "alert alert-danger";
                }
            }
            
            return Page();
        }
    }
}

Webshop.UI/Pages/Checkout/RecieptHistory.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ModelDTO;
using Webshop.UI.DataAccess;

namespace Webshop.UI.Pages.Checkout
{
    public class RecieptHistoryModel : PageModel
    {
        private readonly IDataAccess _dataaccess;

        public RecieptHistoryModel(IDataAccess dataaccess)
        {
            _dataaccess = dataaccess;
        }
        public ShoppingCartDTO Cart { get; set; }
        public void OnGet(int id)
        {
            Cart = _dataaccess.GetShoppingCart(id);
        }
        
    }
}

Webshop.UI/Pages/StorePage/LoggedinIndex.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ModelDTO;
using Webshop.UI.DataAccess;

namespace Webshop.UI.Pages.StorePage
{
    public class LoggedinIndexModel : PageModel
    {
        private readonly IDataAccess _dataaccess;
        [BindProperty]
        public List<ProductsDTO> Products { get; set; }
        [BindProperty]
        public string Productname { get; set; }
        [BindProperty]
        public ShoppingCartDTO ShoppingCart { get; set; }
        public LoggedinIndexModel(IDataAccess dataaccess)
        {
            _dataaccess = dataaccess;
        }
        public void OnGet(int id)
        {
            Products = _dataaccess.GetAllProducts().ToList();
            var cart = _dataaccess.GetAllCarts().ToList().SingleOrDefault(cart => cart.CartId == id);

            if (cart != null)
            {
                ShoppingCart = _dataaccess.GetCartById(id);
            }
            else
            {
                ShoppingCart = _dataaccess.CreateCart(id);
            }
            
        }
        public IActionResult OnPostSearch(int id)
        {
            Products = _dataaccess.GetAllProducts().ToList();
            ShoppingCart = _dataaccess.GetShoppingCart(id);
            
            if (!string.IsNullOrEmpty(Productname))
            {
                Products = Products.Where(p => p.Name.ToLower().Contains(Productname.ToLower())).ToList();
                return Page();
            }

            return RedirectToPage("/StorePage/LoggedinIndex", new { id = ShoppingCart.CartId});
        }
        public void OnGetAddToCart(int id, int product)
        {
            if (ModelState.IsValid)
            {
                ProductsDTO products = _dataaccess.GetProductById(product);
                _dataaccess.AddToCart(products, id);
                Products = _dataaccess.GetAllProducts().ToList();
                ShoppingCart = _dataaccess.GetShoppingCart(id);
            }
            
        }
        public IActionResult OnPostGoBack()
        {
            if (ModelState.IsValid)
            {
                return RedirectToPage("/StorePage/LoggedinIndex", "ShoppingCart");
            }
            return Page();
        }
        public void OnGetMax(int id)
        {
            ShoppingCart = _dataaccess.GetShoppingCart(id);
            Products = _dataaccess.MaxPrice();
        }
        public void OnGetSortMin(int id)
        {
            ShoppingCart = _dataaccess.GetShoppingCart(id);
            Products = _dataaccess.MinPrice();
        }
    }
}

Webshop.UI/Pages/Checkout/Checkout.cshtml
@page
@model Webshop.UI.Pages.Checkout.CheckoutModel
@{
    var totalprice = 0;
    foreach (var item in Model.Cart.CartItems)
    {
        totalprice += item.Price;
    }
}

<br />
<h1>Checkout</h1>
<br />

<a class="btn btn-light" asp-page-handler="GoBack">Go Back</a>
<br />
<form asp-page-handler="pay" asp-route-id="@Model.Cart.CartId">
    <div class="form-group">
        <label asp-for="card.CreditCardNumber">Creditcart number: </label>
        <input asp-for="card.CreditCardNumber" class="form-control">
    </div>
    <div class="form-group">
        <br />
        <label asp-for="card.SecurityCode">Security code: </label>
        <input asp-for="card.SecurityCode" class="form-control">
    </div>
    <br />
    <span asp-validation-for="card.CreditCardNumber" class=@Model.Alert role="alert"> @Model.Feedback </span>
    <br />
    <button type="submit" class="btn btn-white">Pay</button>
</form>
<br />
<h6>Total cost: @totalprice $</h6>

Webshop.UI/Pages/Checkout/RecieptHistory.cshtml
@page
@model Webshop.UI.Pages.Checkout.RecieptHistoryModel
@{

}
<br />
<a class="btn btn-light" asp-page="/StorePage/LoggedinIndex" asp-route-id="@Model.Cart.CartId" asp-page-handler="GoBack">Go Back</a>
<br />
<br />
<h1>Payment Successful!</h1>
<br />