Webshop.UI/Pages/ShoppingCart/ShoppingCart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ModelDTO;
using Webshop.UI.DataAccess;

namespace Webshop.UI.Pages.ShoppingCart
{
    public class ShoppingCartModel : PageModel
    {
        private readonly IDataAccess _dataaccess;
        [BindProperty]
        public ShoppingCartDTO Cart { get; set; }
        public ShoppingCartModel(IDataAccess dataaccess)
        {
            _dataaccess = dataaccess;
        }
        public void OnGet(int id)
        {
            Cart = _dataaccess.GetShoppingCart(id);
        }
       public void OnGetClearCart(int id)
        {
            if (ModelState.IsValid)
            {
                Cart = _dataaccess.GetShoppingCart(id);
                _dataaccess.ClearCartById(id);
            }

        }
    }
}

Webshop.UI/Pages/StorePage/LoggedinIndex.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ModelDTO;
using Webshop.UI.DataAccess;

namespace Webshop.UI.Pages.StorePage
{
    public class LoggedinIndexModel : PageModel
    {
        private readonly IDataAccess _dataaccess;
        [BindProperty]
        public List<ProductsDTO> Products { get; set; }
        [BindProperty]
        public string Productname { get; set; }
        [BindProperty]
        public ShoppingCartDTO ShoppingCart { get; set; }
        public LoggedinIndexModel(IDataAccess dataaccess)
        {
            _dataaccess = dataaccess;
        }
        public void OnGet(int id)
        {
            Products = _dataaccess.GetAllProducts().ToList();
            var cart = _dataaccess.GetAllCarts().ToList().SingleOrDefault(cart => cart.CartId == id);

            if (cart != null)
            {
                ShoppingCart = _dataaccess.GetCartById(id);
            }
            else
            {
                ShoppingCart = _dataaccess.CreateCart(id);
            }
            
        }
        public IActionResult OnPostSearch(int id)
        {
            Products = _dataaccess.GetAllProducts().ToList();
            ShoppingCart = _dataaccess.GetShoppingCart(id);
            
            if (!string.IsNullOrEmpty(Productname))
            {
                Products = Products.Where(p => p.Name.ToLower().Contains(Productname.ToLower())).ToList();
                return Page();
            }

            return RedirectToPage("/StorePage/LoggedinIndex", new { id = ShoppingCart.CartId});
        }
        public void OnGetAddToCart(int id, int product)
        {
            if (ModelState.IsValid)
            {
                ProductsDTO products = _dataaccess.GetProductById(product);
                _dataaccess.AddToCart(products, id);
                Products = _dataaccess.GetAllProducts().ToList();
                ShoppingCart = _dataaccess.GetShoppingCart(id);
            }
            
        }
        public IActionResult OnPostGoBack()
        {
            if (ModelState.IsValid)
            {
                return RedirectToPage("/StorePage/LoggedinIndex", "ShoppingCart");
            }
            return Page();
        }
        public void OnGetMax(int id)
        {
            ShoppingCart = _dataaccess.GetShoppingCart(id);
            Products = _dataaccess.MaxPrice();
        }
        public void OnGetSortMin(int id)
        {
            ShoppingCart = _dataaccess.GetShoppingCart(id);
            Products = _dataaccess.MinPrice();
        }
    }
}

Webshop.UI/Pages/ShoppingCart/ShoppingCart.cshtml
@page
@model Webshop.UI.Pages.ShoppingCart.ShoppingCartModel
@{
    var totalprice = 0;
    @if (Model.Cart.CartItems != null)
    {
        foreach (var item in Model.Cart.CartItems)
        {
            totalprice += item.Price;
        }
    }
    else
    {
        totalprice = 0;
    }

}

<h1>Shopping Cart</h1>
<br />
@if (totalprice == 0)
{

}
else
{
    <a class="btn btn-light" asp-route-id="@Model.Cart.CartId" asp-page-handler="ClearCart">Clear Cart</a>
}
<br />
@if (Model.Cart.CartItems != null)
{
    @foreach (var item in Model.Cart.CartItems)
    {
        <div class="text-center">
            <img src="@item.Image" alt="Alternate Text" />
            <h6>Name : @item.Name</h6>
            <h6>Price: @item.Price $</h6>
            <br />
        </div>
    }
}
else
{
    <br />
    <div class="text-center">
        <h3>You have nothing in the basket</h3>
        <br />
    </div>

}

<div class="text-center"><h6>Amount: @totalprice $</h6></div>

<br />
<div class="text-center">
    <a class="btn btn-light" asp-page="/StorePage/LoggedinIndex" asp-route-id="@Model.Cart.CartId" asp-page-handler="GoBack">Go Back</a>
    @if (totalprice == 0)
    {

    }
    else
    {
        <a class="btn btn-light" asp-page="/Checkout/Checkout" asp-route-id="@Model.Cart.CartId" asp-page-handler="Checkout">Checkout</a>
    }

</div>