Webshop.UI/Pages/StorePage/LoggedinIndex.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ModelDTO;
using Webshop.UI.DataAccess;

namespace Webshop.UI.Pages.StorePage
{
    public class LoggedinIndexModel : PageModel
    {
        private readonly IDataAccess _dataaccess;
        [BindProperty]
        public List<ProductsDTO> Products { get; set; }
        [BindProperty]
        public string Productname { get; set; }
        [BindProperty]
        public ShoppingCartDTO ShoppingCart { get; set; }
        public LoggedinIndexModel(IDataAccess dataaccess)
        {
            _dataaccess = dataaccess;
        }
        public void OnGet(int id)
        {
            Products = _dataaccess.GetAllProducts().ToList();
            var cart = _dataaccess.GetAllCarts().ToList().SingleOrDefault(cart => cart.CartId == id);

            if (cart != null)
            {
                ShoppingCart = _dataaccess.GetCartById(id);
            }
            else
            {
                ShoppingCart = _dataaccess.CreateCart(id);
            }
            
        }
        public IActionResult OnPostSearch(int id)
        {
            Products = _dataaccess.GetAllProducts().ToList();
            ShoppingCart = _dataaccess.GetShoppingCart(id);
            
            if (!string.IsNullOrEmpty(Productname))
            {
                Products = Products.Where(p => p.Name.ToLower().Contains(Productname.ToLower())).ToList();
                return Page();
            }

            return RedirectToPage("/StorePage/LoggedinIndex", new { id = ShoppingCart.CartId});
        }
        public void OnGetAddToCart(int id, int product)
        {
            if (ModelState.IsValid)
            {
                ProductsDTO products = _dataaccess.GetProductById(product);
                _dataaccess.AddToCart(products, id);
                Products = _dataaccess.GetAllProducts().ToList();
                ShoppingCart = _dataaccess.GetShoppingCart(id);
            }
            
        }
        public IActionResult OnPostGoBack()
        {
            if (ModelState.IsValid)
            {
                return RedirectToPage("/StorePage/LoggedinIndex", "ShoppingCart");
            }
            return Page();
        }
        public void OnGetMax(int id)
        {
            ShoppingCart = _dataaccess.GetShoppingCart(id);
            Products = _dataaccess.MaxPrice();
        }
        public void OnGetSortMin(int id)
        {
            ShoppingCart = _dataaccess.GetShoppingCart(id);
            Products = _dataaccess.MinPrice();
        }
    }
}

Webshop.UI/Pages/StorePage/LoggedinIndex.cshtml
@page
@model Webshop.UI.Pages.StorePage.LoggedinIndexModel
@{
}
<form asp-page-handler="Search" asp-route-id="@Model.ShoppingCart.CartId">
    <div class="d-flex">
        <div class="input-group">
            <input class="form-control" placeholder="Search for specific product" asp-for="Productname" />
            <br />
            <div class="input-group-append">
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </div>
    </div>
</form>

<br />
<a class="btn btn-light" asp-route-id="@Model.ShoppingCart.CartId" asp-page-handler="SortMax">Sort by Max Price</a>
<a class="btn btn-light" asp-route-id="@Model.ShoppingCart.CartId" asp-page-handler="SortMin">Sort by Min Price</a>
<br />
<br />  
<h1>Products</h1>
<br />

<div class="text-center">
    <a class="btn btn-light" asp-page="/ShoppingCart/ShoppingCart" asp-route-id="@Model.ShoppingCart.CartId" asp-page-handler="Checkout">Checkout</a>
</div>
<br />
@foreach (var item in Model.Products)
{
    <div asp-page-handler="Index" class="text-center">
        <img src="@item.Image" alt="Card image cap" class="img-thumbnail" />
        <h6>Product : @item.Name</h6>
        <h6>Price : @item.Price$</h6>
        <a class="btn btn-light" asp-page="/StorePage/LoggedinIndex" asp-route-product="@item.id" asp-route-id="@Model.ShoppingCart.CartId" asp-page-handler="AddToCart">Add To Cart</a>
        <br />
        
    </div>
}