Webshop.UI/Pages/Edit/Customers.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ModelDTO;
using Webshop.UI.DataAccess;

namespace Webshop.UI.Pages.Edit
{
    public class CustomersModel : PageModel
    {
        private readonly IDataAccess _dataaccess;
        
        public CustomersModel(IDataAccess dataaccess)
        {
            _dataaccess = dataaccess;
        }
        [BindProperty]
        public int Id { get; set; }
        [BindProperty]
        public List<CustomersDTO> Customers { get; set; }
        public void OnGet()
        {
            Customers = _dataaccess.GetAllCustomers().ToList();
        }
        public IActionResult OnPostEdit()
        {
            if (ModelState.IsValid)
            {
                return RedirectToPage("/Edit/EditCustomers", "Customers", new { id = Id });
            }
            return Page();
        }
    }
}

Webshop.UI/Pages/Edit/EditCustomers.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ModelDTO;
using Webshop.UI.DataAccess;

namespace Webshop.UI.Pages.Edit
{
    public class EditCustomersModel : PageModel
    {
        private readonly IDataAccess _dataaccess;
        public EditCustomersModel(IDataAccess dataaccess)
        {
            _dataaccess = dataaccess;
        }
        [BindProperty]
        public CustomersDTO Customer { get; set; }
        public void OnGet(int id)
        {
            Customer = _dataaccess.GetCustomerById(id);
        }
        public IActionResult OnPostSave()
        {
            if (ModelState.IsValid)
            {
                _dataaccess.EditCustomer(Customer);
                return RedirectToPage("/Edit/Customers");
            }
            return Page();
        }
    }
}

Webshop.UI/Pages/Edit/EditProduct.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ModelDTO;
using Newtonsoft.Json;
using Webshop.UI.DataAccess;

namespace Webshop.UI.Pages.Edit
{
    public class EditProductModel : PageModel
    {
        private readonly IDataAccess _dataaccess;

        public EditProductModel(IDataAccess dataaccess)
        {
            _dataaccess = dataaccess;
        }
        [BindProperty]
        public ProductsDTO Product { get; set; }
        public void OnGet(int id)
        {
            Product = _dataaccess.GetProductById(id);
        }

        public IActionResult OnPostSave()
        {
            if (ModelState.IsValid)
            {
                _dataaccess.EditItems(Product);
                return RedirectToPage("/Edit/Products");
            }
            return Page();
        }
    }
}

Webshop.UI/Pages/Edit/Products.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ModelDTO;
using Newtonsoft.Json;
using Webshop.UI.DataAccess;

namespace Webshop.UI.Pages.Edit
{
    public class ProductsModel : PageModel
    {
        private readonly IDataAccess _dataaccess;
        public ProductsModel(IDataAccess dataaccess)
        {
            _dataaccess = dataaccess;
        }
        [BindProperty]
        public int Id { get; set; }
        [BindProperty]
        public List<ProductsDTO> Prods { get; set; }
        public void OnGet()
        {
            Prods = _dataaccess.GetAllProducts().ToList();
        }

        public IActionResult OnPostEdit()
        {
            if (ModelState.IsValid)
            {
                return RedirectToPage("/Edit/EditProduct", "Products", new { id = Id });
            }
            return Page();
        }
    }
}

Webshop.UI/Pages/EditProducts/EditProduct.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ModelDTO;
using Newtonsoft.Json;
using Webshop.UI.DataAccess;

namespace Webshop.UI.Pages.EditProducts
{
    public class EditProductModel : PageModel
    {
        private readonly IDataAccess _dataaccess;

        public EditProductModel(IDataAccess dataaccess)
        {
            _dataaccess = dataaccess;
        }
        [BindProperty]
        public ProductsDTO Product { get; set; }
        public void OnGet(int id)
        {
            Product = _dataaccess.GetProductById(id);
        }

        public IActionResult OnPostSave()
        {
            if (ModelState.IsValid)
            {
                _dataaccess.EditItems(Product);
                return RedirectToPage("/EditProducts/Products");
            }
            return Page();
        }
    }
}

Webshop.UI/Pages/EditProducts/Products.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ModelDTO;
using Newtonsoft.Json;
using Webshop.UI.DataAccess;

namespace Webshop.UI.Pages.EditProducts
{
    public class ProductsModel : PageModel
    {
        private readonly IDataAccess _dataaccess;
        public List<CustomersDTO> Customer { get; set; }
        public ProductsModel(IDataAccess dataaccess)
        {
            _dataaccess = dataaccess;
        }
        [BindProperty]
        public int Id { get; set; }
        [BindProperty]
        public List<ProductsDTO> Prods { get; set; }
        public void OnGet()
        {
            Prods = _dataaccess.GetAllProducts().ToList();
            Customer = _dataaccess.GetAllCustomers().ToList();
        }

        public IActionResult OnPostEdit()
        {
            if (ModelState.IsValid)
            {
                return RedirectToPage("/EditProducts/EditProduct", "Products", new { id = Id });
            }
            return Page();
        }
    }
}

Webshop.UI/Pages/Products/Products.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataSource_DB;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ModelDTO;
using Webshop.UI.DataAccess;

namespace Webshop.UI.Pages.Products
{
    public class ProductsModel : PageModel
    {
        private readonly IDataAccess _dataaccess;
        private readonly IDataSource _datasource;
        public ProductsModel(IDataSource datasource, IDataAccess dataAccess)
        {
            _datasource = datasource;
            _dataaccess = dataAccess;
        }
        [BindProperty]
        public int Id { get; set; }
        public List<ProductsDTO> Products { get; set; }
        public void OnGet()
        {
            Products = _datasource.GetAllProducts().ToList();
        }
        public IActionResult OnPostAddToCart()
        {
            if (ModelState.IsValid)
            {
                return RedirectToPage("ShoppingCart/ShoppingCart", "ShoppingCart", new { id = Id });
            }
            return Page();
        }
    }
}

Webshop.UI/Pages/Edit/Customers.cshtml
@page
@model Webshop.UI.Pages.Edit.CustomersModel
@{
}

<h1>Customers</h1>
<br />
@foreach (var cust in Model.Customers)
{
    <div class="text-center">
        <h6>Email : @cust.Email</h6>
        <h6>Name : @cust.Name</h6>
        <h6>Password : @cust.Password</h6>
        <h6>Id: @cust.Id</h6>

        <form asp-page-handler="Edit">
            <input type="hidden" asp-for="Id" value="@cust.Id" />
            <br />
            <button type="submit">Edit</button>
            <br />
        </form>
    </div>



}

Webshop.UI/Pages/Edit/EditCustomers.cshtml
@page
@model Webshop.UI.Pages.Edit.EditCustomersModel
@{
}

<h1>Edit Customer</h1>

<h3>@Model.Customer.Name</h3>

<form asp-page-handler="Save">
    <h6>Name: </h6>
    <input type="text" asp-for="Customer.Name" value="@Model.Customer.Name" />
    <h6>Email: </h6>
    <input type="text" asp-for="Customer.Email" value="@Model.Customer.Email" />
    <h6>Password: </h6>
    <input type="text" asp-for="Customer.Password" value="@Model.Customer.Password" />
    <h6>Id: </h6>
    <input type="text" asp-for="Customer.Id" value="@Model.Customer.Id" />
    <button type="submit">Save</button>
</form>

Webshop.UI/Pages/Edit/EditProduct.cshtml
@page
@model Webshop.UI.Pages.Edit.EditProductModel
@{
}

<h1>Edit Product</h1>

<h3>@Model.Product.Name</h3>

<form asp-page-handler="Save">
    <h6>Name: </h6>
    <input type="text" asp-for="Product.Name" value="@Model.Product.Name" />
    <h6>Price: </h6>
    <input type="text" asp-for="Product.Price" value="@Model.Product.Price" />
    <h6>Message: </h6>
    <input type="text" asp-for="Product.Message" value="@Model.Product.Message" />
    <input type="hidden" asp-for="Product.id" value="@Model.Product.id" />
    <button type="submit">Save</button>
</form>

Webshop.UI/Pages/Edit/Products.cshtml
@page
@model Webshop.UI.Pages.Edit.ProductsModel
@{
}

<h1>Products</h1>
<br />
@foreach (var prod in Model.Prods)
{
<div class="text-center">
    <img src="@prod.Image" alt="Card image cap" class="img-thumbnail" />
    <h6>Product : @prod.Name</h6>
    <h6>Price : @prod.Price$</h6>
    <h6>Message: @prod.Message</h6>

        <form asp-page-handler="Edit">
            <input type="hidden" asp-for="Id" value="@prod.id" />
            <br />
            <button type="submit">Edit</button>
            <br />
        </form>
    </div>

        

}